import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/main.scss";
import CommonLayout from "@/components/CommonLayout";
import { Inter,JetBrains_Mono } from "next/font/google";
import { Providers } from "./providers";
import ScrollToTop from "@/components/ScrollToTop";


const inter = Inter({ subsets: ["latin"],
  variable:"--font-primary"
 });
const jet_brain = JetBrains_Mono({ subsets: ["latin"],
  variable:"--font-secondary"
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jet_brain.variable} ${inter.variable} antialiased`}
      >
        <Providers>
          <ScrollToTop />
 
          <CommonLayout>{children}</CommonLayout>
        </Providers>
      </body>
    </html>
  );
}
